config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  get "signin" => "sessions#new", as: :signin
  post "signin" => "sessions#create"
  get "signout" => "sessions#destroy", as: :signout
  get "/categories" => "categories#index", as: :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base

  validates :image, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :ensure_current_user

  def ensure_current_user
    redirect_to signin_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order(:name)
  end

end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @user = User.new(email: params[:user][:email])
      @user.errors[:base] << "Username / password is invalid"
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to signin_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2>Categories</h2>
<ul>
  <% @categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
</ul>

app/views/kittens/_kitten.html.erb
<div class="kitten">
  <%= image_tag kitten.image %>
</div>

app/views/kittens/index.html.erb
<h1>Kittens!</h1>

<div class="kittens-container">
  <%= render @kittens %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Practice</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="container">
    <div class="logo">
      <%= link_to "Kittens!", root_path %>
    </div>
    <%= link_to "Categories", categories_path %>
    <% if current_user %>
      <div class="logout">
        <%= current_user.email %> |
        <%= link_to "Logout", signout_path %>
      </div>
    <% end %>
  </div>
</header>
<main>
  <div class="container">
    <%= yield %>
  </div>
</main>
</body>
</html>